[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
